import * as flags from "country-flag-icons/react/3x2";
import { CountryKey, type Country } from "@/types/language";

const countries: Country[] = [
  {
    code: "US",
    name: "English",
    key: CountryKey.EN,
    phoneCode: 1,
    flag: "US" as keyof typeof flags,
  },
  {
    code: "ID",
    name: "Indonesian",
    key: CountryKey.ID,
    phoneCode: 62,
    flag: "ID" as keyof typeof flags,
  },
  {
    code: "GB",
    name: "English (UK)",
    key: CountryKey.EN,
    phoneCode: 44,
    flag: "GB" as keyof typeof flags,
  },
  {
    code: "MY",
    name: "Malay",
    key: CountryKey.MS,
    phoneCode: 60,
    flag: "MY" as keyof typeof flags,
  },
  {
    code: "SG",
    name: "English (Singapore)",
    key: CountryKey.EN,
    phoneCode: 65,
    flag: "SG" as keyof typeof flags,
  },
  {
    code: "TH",
    name: "Thai",
    key: CountryKey.TH,
    phoneCode: 66,
    flag: "TH" as keyof typeof flags,
  },
  {
    code: "PH",
    name: "Filipino",
    key: CountryKey.FIL,
    phoneCode: 63,
    flag: "PH" as keyof typeof flags,
  },
  {
    code: "VN",
    name: "Vietnamese",
    key: CountryKey.VI,
    phoneCode: 84,
    flag: "VN" as keyof typeof flags,
  },
  {
    code: "CN",
    name: "Chinese",
    key: CountryKey.ZH,
    phoneCode: 86,
    flag: "CN" as keyof typeof flags,
  },
  {
    code: "JP",
    name: "Japanese",
    key: CountryKey.JA,
    phoneCode: 81,
    flag: "JP" as keyof typeof flags,
  },
  {
    code: "KR",
    name: "Korean",
    key: CountryKey.KO,
    phoneCode: 82,
    flag: "KR" as keyof typeof flags,
  },
  {
    code: "IN",
    name: "Hindi",
    key: CountryKey.HI,
    phoneCode: 91,
    flag: "IN" as keyof typeof flags,
  },
  {
    code: "AU",
    name: "English (Australia)",
    key: CountryKey.EN,
    phoneCode: 61,
    flag: "AU" as keyof typeof flags,
  },
  {
    code: "NZ",
    name: "English (New Zealand)",
    key: CountryKey.EN,
    phoneCode: 64,
    flag: "NZ" as keyof typeof flags,
  },
  {
    code: "FR",
    name: "French",
    key: CountryKey.FR,
    phoneCode: 33,
    flag: "FR" as keyof typeof flags,
  },
  {
    code: "DE",
    name: "German",
    key: CountryKey.DE,
    phoneCode: 49,
    flag: "DE" as keyof typeof flags,
  },
  {
    code: "IT",
    name: "Italian",
    key: CountryKey.IT,
    phoneCode: 39,
    flag: "IT" as keyof typeof flags,
  },
  {
    code: "ES",
    name: "Spanish",
    key: CountryKey.ES,
    phoneCode: 34,
    flag: "ES" as keyof typeof flags,
  },
  {
    code: "PT",
    name: "Portuguese",
    key: CountryKey.PT,
    phoneCode: 351,
    flag: "PT" as keyof typeof flags,
  },
  {
    code: "NL",
    name: "Dutch",
    key: CountryKey.NL,
    phoneCode: 31,
    flag: "NL" as keyof typeof flags,
  },
  {
    code: "BR",
    name: "Portuguese (Brazil)",
    key: CountryKey.PT,
    phoneCode: 55,
    flag: "BR" as keyof typeof flags,
  },
  {
    code: "MX",
    name: "Spanish (Mexico)",
    key: CountryKey.ES,
    phoneCode: 52,
    flag: "MX" as keyof typeof flags,
  },
  {
    code: "AR",
    name: "Spanish (Argentina)",
    key: CountryKey.ES,
    phoneCode: 54,
    flag: "AR" as keyof typeof flags,
  },
  {
    code: "RU",
    name: "Russian",
    key: CountryKey.RU,
    phoneCode: 7,
    flag: "RU" as keyof typeof flags,
  },
  {
    code: "SA",
    name: "Arabic",
    key: CountryKey.AR,
    phoneCode: 966,
    flag: "SA" as keyof typeof flags,
  },
  {
    code: "AE",
    name: "Arabic (UAE)",
    key: CountryKey.AR,
    phoneCode: 971,
    flag: "AE" as keyof typeof flags,
  },
  {
    code: "TR",
    name: "Turkish",
    key: CountryKey.TR,
    phoneCode: 90,
    flag: "TR" as keyof typeof flags,
  },
  {
    code: "EG",
    name: "Arabic (Egypt)",
    key: CountryKey.AR,
    phoneCode: 20,
    flag: "EG" as keyof typeof flags,
  },
  {
    code: "ZA",
    name: "English (South Africa)",
    key: CountryKey.EN,
    phoneCode: 27,
    flag: "ZA" as keyof typeof flags,
  },
  {
    code: "CA",
    name: "English (Canada)",
    key: CountryKey.EN,
    phoneCode: 1,
    flag: "CA" as keyof typeof flags,
  },
  {
    code: "PL",
    name: "Polish",
    key: CountryKey.PL,
    phoneCode: 48,
    flag: "PL" as keyof typeof flags,
  },
  {
    code: "SE",
    name: "Swedish",
    key: CountryKey.SV,
    phoneCode: 46,
    flag: "SE" as keyof typeof flags,
  },
  {
    code: "NO",
    name: "Norwegian",
    key: CountryKey.NO,
    phoneCode: 47,
    flag: "NO" as keyof typeof flags,
  },
  {
    code: "DK",
    name: "Danish",
    key: CountryKey.DA,
    phoneCode: 45,
    flag: "DK" as keyof typeof flags,
  },
  {
    code: "FI",
    name: "Finnish",
    key: CountryKey.FI,
    phoneCode: 358,
    flag: "FI" as keyof typeof flags,
  },
  {
    code: "GR",
    name: "Greek",
    key: CountryKey.EL,
    phoneCode: 30,
    flag: "GR" as keyof typeof flags,
  },
  {
    code: "CZ",
    name: "Czech",
    key: CountryKey.CS,
    phoneCode: 420,
    flag: "CZ" as keyof typeof flags,
  },
  {
    code: "HU",
    name: "Hungarian",
    key: CountryKey.HU,
    phoneCode: 36,
    flag: "HU" as keyof typeof flags,
  },
  {
    code: "RO",
    name: "Romanian",
    key: CountryKey.RO,
    phoneCode: 40,
    flag: "RO" as keyof typeof flags,
  },
  {
    code: "UA",
    name: "Ukrainian",
    key: CountryKey.UK,
    phoneCode: 380,
    flag: "UA" as keyof typeof flags,
  },
  {
    code: "IL",
    name: "Hebrew",
    key: CountryKey.HE,
    phoneCode: 972,
    flag: "IL" as keyof typeof flags,
  },
  {
    code: "PK",
    name: "Urdu",
    key: CountryKey.UR,
    phoneCode: 92,
    flag: "PK" as keyof typeof flags,
  },
  {
    code: "BD",
    name: "Bengali",
    key: CountryKey.BN,
    phoneCode: 880,
    flag: "BD" as keyof typeof flags,
  },
  {
    code: "LK",
    name: "Sinhala",
    key: CountryKey.SI,
    phoneCode: 94,
    flag: "LK" as keyof typeof flags,
  },
  {
    code: "MM",
    name: "Burmese",
    key: CountryKey.MY,
    phoneCode: 95,
    flag: "MM" as keyof typeof flags,
  },
  {
    code: "KH",
    name: "Khmer",
    key: CountryKey.KM,
    phoneCode: 855,
    flag: "KH" as keyof typeof flags,
  },
  {
    code: "LA",
    name: "Lao",
    key: CountryKey.LO,
    phoneCode: 856,
    flag: "LA" as keyof typeof flags,
  },
  {
    code: "NP",
    name: "Nepali",
    key: CountryKey.NE,
    phoneCode: 977,
    flag: "NP" as keyof typeof flags,
  },
  {
    code: "NG",
    name: "English (Nigeria)",
    key: CountryKey.EN,
    phoneCode: 234,
    flag: "NG" as keyof typeof flags,
  },
  {
    code: "KE",
    name: "English (Kenya)",
    key: CountryKey.EN,
    phoneCode: 254,
    flag: "KE" as keyof typeof flags,
  },
  {
    code: "GH",
    name: "English (Ghana)",
    key: CountryKey.EN,
    phoneCode: 233,
    flag: "GH" as keyof typeof flags,
  },
  {
    code: "ET",
    name: "Amharic",
    key: CountryKey.AM,
    phoneCode: 251,
    flag: "ET" as keyof typeof flags,
  },
  {
    code: "TZ",
    name: "Swahili",
    key: CountryKey.SW,
    phoneCode: 255,
    flag: "TZ" as keyof typeof flags,
  },
  {
    code: "UG",
    name: "English (Uganda)",
    key: CountryKey.EN,
    phoneCode: 256,
    flag: "UG" as keyof typeof flags,
  },
  {
    code: "MA",
    name: "Arabic (Morocco)",
    key: CountryKey.AR,
    phoneCode: 212,
    flag: "MA" as keyof typeof flags,
  },
  {
    code: "DZ",
    name: "Arabic (Algeria)",
    key: CountryKey.AR,
    phoneCode: 213,
    flag: "DZ" as keyof typeof flags,
  },
  {
    code: "TN",
    name: "Arabic (Tunisia)",
    key: CountryKey.AR,
    phoneCode: 216,
    flag: "TN" as keyof typeof flags,
  },
  {
    code: "CL",
    name: "Spanish (Chile)",
    key: CountryKey.ES,
    phoneCode: 56,
    flag: "CL" as keyof typeof flags,
  },
  {
    code: "CO",
    name: "Spanish (Colombia)",
    key: CountryKey.ES,
    phoneCode: 57,
    flag: "CO" as keyof typeof flags,
  },
  {
    code: "PE",
    name: "Spanish (Peru)",
    key: CountryKey.ES,
    phoneCode: 51,
    flag: "PE" as keyof typeof flags,
  },
  {
    code: "VE",
    name: "Spanish (Venezuela)",
    key: CountryKey.ES,
    phoneCode: 58,
    flag: "VE" as keyof typeof flags,
  },
  {
    code: "IE",
    name: "English (Ireland)",
    key: CountryKey.EN,
    phoneCode: 353,
    flag: "IE" as keyof typeof flags,
  },
  {
    code: "BE",
    name: "Dutch (Belgium)",
    key: CountryKey.NL,
    phoneCode: 32,
    flag: "BE" as keyof typeof flags,
  },
  {
    code: "CH",
    name: "German (Switzerland)",
    key: CountryKey.DE,
    phoneCode: 41,
    flag: "CH" as keyof typeof flags,
  },
  {
    code: "AT",
    name: "German (Austria)",
    key: CountryKey.DE,
    phoneCode: 43,
    flag: "AT" as keyof typeof flags,
  },
].sort((a, b) => a.name.localeCompare(b.name));

export default countries;
