import * as flags from "country-flag-icons/react/3x2";
import { LanguageKey, type Language, type Country } from "@/types/world";

export const languages: Record<LanguageKey, Language> = {
  [LanguageKey.EN]: {
    name: "English",
    flag: "US" as keyof typeof flags,
  },
  [LanguageKey.ID]: {
    name: "Indonesian",
    flag: "ID" as keyof typeof flags,
  },
  [LanguageKey.MS]: {
    name: "Malay",
    flag: "MY" as keyof typeof flags,
  },
  [LanguageKey.TH]: {
    name: "Thai",
    flag: "TH" as keyof typeof flags,
  },
  [LanguageKey.FIL]: {
    name: "Filipino",
    flag: "PH" as keyof typeof flags,
  },
  [LanguageKey.VI]: {
    name: "Vietnamese",
    flag: "VN" as keyof typeof flags,
  },
  [LanguageKey.ZH]: {
    name: "Chinese",
    flag: "CN" as keyof typeof flags,
  },
  [LanguageKey.JA]: {
    name: "Japanese",
    flag: "JP" as keyof typeof flags,
  },
  [LanguageKey.KO]: {
    name: "Korean",
    flag: "KR" as keyof typeof flags,
  },
  [LanguageKey.HI]: {
    name: "Hindi",
    flag: "IN" as keyof typeof flags,
  },
  [LanguageKey.FR]: {
    name: "French",
    flag: "FR" as keyof typeof flags,
  },
  [LanguageKey.DE]: {
    name: "German",
    flag: "DE" as keyof typeof flags,
  },
  [LanguageKey.IT]: {
    name: "Italian",
    flag: "IT" as keyof typeof flags,
  },
  [LanguageKey.ES]: {
    name: "Spanish",
    flag: "ES" as keyof typeof flags,
  },
  [LanguageKey.PT]: {
    name: "Portuguese",
    flag: "PT" as keyof typeof flags,
  },
  [LanguageKey.NL]: {
    name: "Dutch",
    flag: "NL" as keyof typeof flags,
  },
  [LanguageKey.RU]: {
    name: "Russian",
    flag: "RU" as keyof typeof flags,
  },
  [LanguageKey.AR]: {
    name: "Arabic",
    flag: "SA" as keyof typeof flags,
  },
  [LanguageKey.TR]: {
    name: "Turkish",
    flag: "TR" as keyof typeof flags,
  },
  [LanguageKey.PL]: {
    name: "Polish",
    flag: "PL" as keyof typeof flags,
  },
  [LanguageKey.SV]: {
    name: "Swedish",
    flag: "SE" as keyof typeof flags,
  },
  [LanguageKey.NO]: {
    name: "Norwegian",
    flag: "NO" as keyof typeof flags,
  },
  [LanguageKey.DA]: {
    name: "Danish",
    flag: "DK" as keyof typeof flags,
  },
  [LanguageKey.FI]: {
    name: "Finnish",
    flag: "FI" as keyof typeof flags,
  },
  [LanguageKey.EL]: {
    name: "Greek",
    flag: "GR" as keyof typeof flags,
  },
  [LanguageKey.CS]: {
    name: "Czech",
    flag: "CZ" as keyof typeof flags,
  },
  [LanguageKey.HU]: {
    name: "Hungarian",
    flag: "HU" as keyof typeof flags,
  },
  [LanguageKey.RO]: {
    name: "Romanian",
    flag: "RO" as keyof typeof flags,
  },
  [LanguageKey.UK]: {
    name: "Ukrainian",
    flag: "UA" as keyof typeof flags,
  },
  [LanguageKey.HE]: {
    name: "Hebrew",
    flag: "IL" as keyof typeof flags,
  },
  [LanguageKey.UR]: {
    name: "Urdu",
    flag: "PK" as keyof typeof flags,
  },
  [LanguageKey.BN]: {
    name: "Bengali",
    flag: "BD" as keyof typeof flags,
  },
  [LanguageKey.SI]: {
    name: "Sinhala",
    flag: "LK" as keyof typeof flags,
  },
  [LanguageKey.MY]: {
    name: "Burmese",
    flag: "MM" as keyof typeof flags,
  },
  [LanguageKey.KM]: {
    name: "Khmer",
    flag: "KH" as keyof typeof flags,
  },
  [LanguageKey.LO]: {
    name: "Lao",
    flag: "LA" as keyof typeof flags,
  },
  [LanguageKey.NE]: {
    name: "Nepali",
    flag: "NP" as keyof typeof flags,
  },
  [LanguageKey.AM]: {
    name: "Amharic",
    flag: "ET" as keyof typeof flags,
  },
  [LanguageKey.SW]: {
    name: "Swahili",
    flag: "KE" as keyof typeof flags,
  },
};

export const countries: Country[] = [
  {
    code: "US",
    name: "English",
    language_key: LanguageKey.EN,
    phoneCode: 1,
    flag: "US" as keyof typeof flags,
  },
  {
    code: "ID",
    name: "Indonesian",
    language_key: LanguageKey.ID,
    phoneCode: 62,
    flag: "ID" as keyof typeof flags,
  },
  {
    code: "GB",
    name: "English (UK)",
    language_key: LanguageKey.EN,
    phoneCode: 44,
    flag: "GB" as keyof typeof flags,
  },
  {
    code: "MY",
    name: "Malay",
    language_key: LanguageKey.MS,
    phoneCode: 60,
    flag: "MY" as keyof typeof flags,
  },
  {
    code: "SG",
    name: "English (Singapore)",
    language_key: LanguageKey.EN,
    phoneCode: 65,
    flag: "SG" as keyof typeof flags,
  },
  {
    code: "TH",
    name: "Thai",
    language_key: LanguageKey.TH,
    phoneCode: 66,
    flag: "TH" as keyof typeof flags,
  },
  {
    code: "PH",
    name: "Filipino",
    language_key: LanguageKey.FIL,
    phoneCode: 63,
    flag: "PH" as keyof typeof flags,
  },
  {
    code: "VN",
    name: "Vietnamese",
    language_key: LanguageKey.VI,
    phoneCode: 84,
    flag: "VN" as keyof typeof flags,
  },
  {
    code: "CN",
    name: "Chinese",
    language_key: LanguageKey.ZH,
    phoneCode: 86,
    flag: "CN" as keyof typeof flags,
  },
  {
    code: "JP",
    name: "Japanese",
    language_key: LanguageKey.JA,
    phoneCode: 81,
    flag: "JP" as keyof typeof flags,
  },
  {
    code: "KR",
    name: "Korean",
    language_key: LanguageKey.KO,
    phoneCode: 82,
    flag: "KR" as keyof typeof flags,
  },
  {
    code: "IN",
    name: "Hindi",
    language_key: LanguageKey.HI,
    phoneCode: 91,
    flag: "IN" as keyof typeof flags,
  },
  {
    code: "AU",
    name: "English (Australia)",
    language_key: LanguageKey.EN,
    phoneCode: 61,
    flag: "AU" as keyof typeof flags,
  },
  {
    code: "NZ",
    name: "English (New Zealand)",
    language_key: LanguageKey.EN,
    phoneCode: 64,
    flag: "NZ" as keyof typeof flags,
  },
  {
    code: "FR",
    name: "French",
    language_key: LanguageKey.FR,
    phoneCode: 33,
    flag: "FR" as keyof typeof flags,
  },
  {
    code: "DE",
    name: "German",
    language_key: LanguageKey.DE,
    phoneCode: 49,
    flag: "DE" as keyof typeof flags,
  },
  {
    code: "IT",
    name: "Italian",
    language_key: LanguageKey.IT,
    phoneCode: 39,
    flag: "IT" as keyof typeof flags,
  },
  {
    code: "ES",
    name: "Spanish",
    language_key: LanguageKey.ES,
    phoneCode: 34,
    flag: "ES" as keyof typeof flags,
  },
  {
    code: "PT",
    name: "Portuguese",
    language_key: LanguageKey.PT,
    phoneCode: 351,
    flag: "PT" as keyof typeof flags,
  },
  {
    code: "NL",
    name: "Dutch",
    language_key: LanguageKey.NL,
    phoneCode: 31,
    flag: "NL" as keyof typeof flags,
  },
  {
    code: "BR",
    name: "Portuguese (Brazil)",
    language_key: LanguageKey.PT,
    phoneCode: 55,
    flag: "BR" as keyof typeof flags,
  },
  {
    code: "MX",
    name: "Spanish (Mexico)",
    language_key: LanguageKey.ES,
    phoneCode: 52,
    flag: "MX" as keyof typeof flags,
  },
  {
    code: "AR",
    name: "Spanish (Argentina)",
    language_key: LanguageKey.ES,
    phoneCode: 54,
    flag: "AR" as keyof typeof flags,
  },
  {
    code: "RU",
    name: "Russian",
    language_key: LanguageKey.RU,
    phoneCode: 7,
    flag: "RU" as keyof typeof flags,
  },
  {
    code: "SA",
    name: "Arabic",
    language_key: LanguageKey.AR,
    phoneCode: 966,
    flag: "SA" as keyof typeof flags,
  },
  {
    code: "AE",
    name: "Arabic (UAE)",
    language_key: LanguageKey.AR,
    phoneCode: 971,
    flag: "AE" as keyof typeof flags,
  },
  {
    code: "TR",
    name: "Turkish",
    language_key: LanguageKey.TR,
    phoneCode: 90,
    flag: "TR" as keyof typeof flags,
  },
  {
    code: "EG",
    name: "Arabic (Egypt)",
    language_key: LanguageKey.AR,
    phoneCode: 20,
    flag: "EG" as keyof typeof flags,
  },
  {
    code: "ZA",
    name: "English (South Africa)",
    language_key: LanguageKey.EN,
    phoneCode: 27,
    flag: "ZA" as keyof typeof flags,
  },
  {
    code: "CA",
    name: "English (Canada)",
    language_key: LanguageKey.EN,
    phoneCode: 1,
    flag: "CA" as keyof typeof flags,
  },
  {
    code: "PL",
    name: "Polish",
    language_key: LanguageKey.PL,
    phoneCode: 48,
    flag: "PL" as keyof typeof flags,
  },
  {
    code: "SE",
    name: "Swedish",
    language_key: LanguageKey.SV,
    phoneCode: 46,
    flag: "SE" as keyof typeof flags,
  },
  {
    code: "NO",
    name: "Norwegian",
    language_key: LanguageKey.NO,
    phoneCode: 47,
    flag: "NO" as keyof typeof flags,
  },
  {
    code: "DK",
    name: "Danish",
    language_key: LanguageKey.DA,
    phoneCode: 45,
    flag: "DK" as keyof typeof flags,
  },
  {
    code: "FI",
    name: "Finnish",
    language_key: LanguageKey.FI,
    phoneCode: 358,
    flag: "FI" as keyof typeof flags,
  },
  {
    code: "GR",
    name: "Greek",
    language_key: LanguageKey.EL,
    phoneCode: 30,
    flag: "GR" as keyof typeof flags,
  },
  {
    code: "CZ",
    name: "Czech",
    language_key: LanguageKey.CS,
    phoneCode: 420,
    flag: "CZ" as keyof typeof flags,
  },
  {
    code: "HU",
    name: "Hungarian",
    language_key: LanguageKey.HU,
    phoneCode: 36,
    flag: "HU" as keyof typeof flags,
  },
  {
    code: "RO",
    name: "Romanian",
    language_key: LanguageKey.RO,
    phoneCode: 40,
    flag: "RO" as keyof typeof flags,
  },
  {
    code: "UA",
    name: "Ukrainian",
    language_key: LanguageKey.UK,
    phoneCode: 380,
    flag: "UA" as keyof typeof flags,
  },
  {
    code: "IL",
    name: "Hebrew",
    language_key: LanguageKey.HE,
    phoneCode: 972,
    flag: "IL" as keyof typeof flags,
  },
  {
    code: "PK",
    name: "Urdu",
    language_key: LanguageKey.UR,
    phoneCode: 92,
    flag: "PK" as keyof typeof flags,
  },
  {
    code: "BD",
    name: "Bengali",
    language_key: LanguageKey.BN,
    phoneCode: 880,
    flag: "BD" as keyof typeof flags,
  },
  {
    code: "LK",
    name: "Sinhala",
    language_key: LanguageKey.SI,
    phoneCode: 94,
    flag: "LK" as keyof typeof flags,
  },
  {
    code: "MM",
    name: "Burmese",
    language_key: LanguageKey.MY,
    phoneCode: 95,
    flag: "MM" as keyof typeof flags,
  },
  {
    code: "KH",
    name: "Khmer",
    language_key: LanguageKey.KM,
    phoneCode: 855,
    flag: "KH" as keyof typeof flags,
  },
  {
    code: "LA",
    name: "Lao",
    language_key: LanguageKey.LO,
    phoneCode: 856,
    flag: "LA" as keyof typeof flags,
  },
  {
    code: "NP",
    name: "Nepali",
    language_key: LanguageKey.NE,
    phoneCode: 977,
    flag: "NP" as keyof typeof flags,
  },
  {
    code: "NG",
    name: "English (Nigeria)",
    language_key: LanguageKey.EN,
    phoneCode: 234,
    flag: "NG" as keyof typeof flags,
  },
  {
    code: "KE",
    name: "English (Kenya)",
    language_key: LanguageKey.EN,
    phoneCode: 254,
    flag: "KE" as keyof typeof flags,
  },
  {
    code: "GH",
    name: "English (Ghana)",
    language_key: LanguageKey.EN,
    phoneCode: 233,
    flag: "GH" as keyof typeof flags,
  },
  {
    code: "ET",
    name: "Amharic",
    language_key: LanguageKey.AM,
    phoneCode: 251,
    flag: "ET" as keyof typeof flags,
  },
  {
    code: "TZ",
    name: "Swahili",
    language_key: LanguageKey.SW,
    phoneCode: 255,
    flag: "TZ" as keyof typeof flags,
  },
  {
    code: "UG",
    name: "English (Uganda)",
    language_key: LanguageKey.EN,
    phoneCode: 256,
    flag: "UG" as keyof typeof flags,
  },
  {
    code: "MA",
    name: "Arabic (Morocco)",
    language_key: LanguageKey.AR,
    phoneCode: 212,
    flag: "MA" as keyof typeof flags,
  },
  {
    code: "DZ",
    name: "Arabic (Algeria)",
    language_key: LanguageKey.AR,
    phoneCode: 213,
    flag: "DZ" as keyof typeof flags,
  },
  {
    code: "TN",
    name: "Arabic (Tunisia)",
    language_key: LanguageKey.AR,
    phoneCode: 216,
    flag: "TN" as keyof typeof flags,
  },
  {
    code: "CL",
    name: "Spanish (Chile)",
    language_key: LanguageKey.ES,
    phoneCode: 56,
    flag: "CL" as keyof typeof flags,
  },
  {
    code: "CO",
    name: "Spanish (Colombia)",
    language_key: LanguageKey.ES,
    phoneCode: 57,
    flag: "CO" as keyof typeof flags,
  },
  {
    code: "PE",
    name: "Spanish (Peru)",
    language_key: LanguageKey.ES,
    phoneCode: 51,
    flag: "PE" as keyof typeof flags,
  },
  {
    code: "VE",
    name: "Spanish (Venezuela)",
    language_key: LanguageKey.ES,
    phoneCode: 58,
    flag: "VE" as keyof typeof flags,
  },
  {
    code: "IE",
    name: "English (Ireland)",
    language_key: LanguageKey.EN,
    phoneCode: 353,
    flag: "IE" as keyof typeof flags,
  },
  {
    code: "BE",
    name: "Dutch (Belgium)",
    language_key: LanguageKey.NL,
    phoneCode: 32,
    flag: "BE" as keyof typeof flags,
  },
  {
    code: "CH",
    name: "German (Switzerland)",
    language_key: LanguageKey.DE,
    phoneCode: 41,
    flag: "CH" as keyof typeof flags,
  },
  {
    code: "AT",
    name: "German (Austria)",
    language_key: LanguageKey.DE,
    phoneCode: 43,
    flag: "AT" as keyof typeof flags,
  },
].sort((a, b) => a.name.localeCompare(b.name));
