import type { MenuItem, OrderCard } from "@/stores/posStore";
import type { WarehouseHistory } from "@/types/warehouse";

export const MONTHS = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];
export const DAYS_30 = Array.from({ length: 30 }, (_, i) => String(i + 1));

export const dummyOrders: OrderCard[] = [
  {
    id: "F0028",
    table: "07",
    items: 3,
    time: "Just Now",
    status: "wait_list",
  },
  {
    id: "F0019",
    table: "09",
    items: 2,
    time: "25 mins ago",
    status: "wait_list",
  },
  {
    id: "F0031",
    table: "12",
    items: 5,
    time: "10 mins ago",
    status: "finish",
  },
  {
    id: "F0033",
    table: "15",
    items: 2,
    time: "5 mins ago",
    status: "wait_list",
  },
  {
    id: "F0034",
    table: "02",
    items: 6,
    time: "30 mins ago",
    status: "process",
  },
  {
    id: "F0035",
    table: "11",
    items: 3,
    time: "1 hour ago",
    status: "finish",
  },
  {
    id: "F0037",
    table: "08",
    items: 1,
    time: "Just Now",
    status: "wait_list",
  },
  {
    id: "F0038",
    table: "14",
    items: 4,
    time: "40 mins ago",
    status: "process",
  },
  {
    id: "F0039",
    table: "20",
    items: 5,
    time: "2 hours ago",
    status: "finish",
  },
  {
    id: "F0041",
    table: "16",
    items: 3,
    time: "1 min ago",
    status: "wait_list",
  },
  {
    id: "F0042",
    table: "06",
    items: 8,
    time: "20 mins ago",
    status: "process",
  },
  {
    id: "F0043",
    table: "18",
    items: 1,
    time: "45 mins ago",
    status: "finish",
  },
  {
    id: "F0045",
    table: "22",
    items: 2,
    time: "3 mins ago",
    status: "wait_list",
  },
  {
    id: "F0046",
    table: "25",
    items: 6,
    time: "35 mins ago",
    status: "process",
  },
  {
    id: "F0047",
    table: "13",
    items: 3,
    time: "1.5 hours ago",
    status: "finish",
  },
  {
    id: "F0049",
    table: "21",
    items: 2,
    time: "4 mins ago",
    status: "wait_list",
  },
  {
    id: "F0050",
    table: "28",
    items: 7,
    time: "50 mins ago",
    status: "process",
  },
  {
    id: "F0051",
    table: "30",
    items: 1,
    time: "3 hours ago",
    status: "finish",
  },
  {
    id: "F0053",
    table: "23",
    items: 4,
    time: "7 mins ago",
    status: "wait_list",
  },
  {
    id: "F0054",
    table: "09",
    items: 2,
    time: "55 mins ago",
    status: "process",
  },
  {
    id: "F0055",
    table: "12",
    items: 5,
    time: "2.5 hours ago",
    status: "finish",
  },
  {
    id: "F0057",
    table: "07",
    items: 2,
    time: "9 mins ago",
    status: "wait_list",
  },
  {
    id: "F0058",
    table: "15",
    items: 3,
    time: "1 hour ago",
    status: "process",
  },
  {
    id: "F0059",
    table: "01",
    items: 4,
    time: "4 hours ago",
    status: "finish",
  },
  {
    id: "F0061",
    table: "14",
    items: 1,
    time: "11 mins ago",
    status: "wait_list",
  },
  {
    id: "F0062",
    table: "20",
    items: 5,
    time: "1.2 hours ago",
    status: "process",
  },
  {
    id: "F0063",
    table: "04",
    items: 2,
    time: "5 hours ago",
    status: "finish",
  },
  {
    id: "F0065",
    table: "06",
    items: 8,
    time: "13 mins ago",
    status: "wait_list",
  },
  {
    id: "F0066",
    table: "18",
    items: 4,
    time: "1.4 hours ago",
    status: "process",
  },
  {
    id: "F0067",
    table: "10",
    items: 6,
    time: "6 hours ago",
    status: "finish",
  },
];

export const categories = [
  {
    key: "all",
    label: { id: "Semua", en: "All" },
    emoji: "📦",
    count: 250,
  },
  {
    key: "electronics",
    label: { id: "Elektronik", en: "Electronics" },
    emoji: "💻",
    count: 42,
  },
  {
    key: "fashion",
    label: { id: "Fashion", en: "Fashion" },
    emoji: "👕",
    count: 85,
  },
  {
    key: "home",
    label: { id: "Rumah Tangga", en: "Home & Living" },
    emoji: "🏠",
    count: 33,
  },
  {
    key: "groceries",
    label: { id: "Sembako", en: "Groceries" },
    emoji: "🛒",
    count: 110,
  },
  {
    key: "beauty",
    label: { id: "Kecantikan", en: "Beauty" },
    emoji: "💄",
    count: 15,
  },
  {
    key: "sports",
    label: { id: "Olahraga", en: "Sports" },
    emoji: "⚽",
    count: 12,
  },
  {
    key: "special",
    label: { id: "Promo Spesial", en: "Special Deals" },
    emoji: "🔥",
    count: 8,
  },
];

export const dummyMenuItems: MenuItem[] = [
  {
    id: 1,
    name: "MacBook Pro M3",
    category: "electronics",
    price: 25000000.0,
    emoji: "💻",
  },
  {
    id: 2,
    name: "iPhone 15 Pro",
    category: "electronics",
    price: 18000000.0,
    emoji: "📱",
  },
  {
    id: 3,
    name: "Oversized T-Shirt",
    category: "fashion",
    price: 150000.0,
    emoji: "👕",
  },
  {
    id: 4,
    name: "Denim Jacket",
    category: "fashion",
    price: 450000.0,
    emoji: "🧥",
  },
  {
    id: 5,
    name: "Air Fryer 4L",
    category: "home",
    price: 850000.0,
    emoji: "🍳",
  },
  {
    id: 6,
    name: "Ergonomic Chair",
    category: "home",
    price: 1200000.0,
    emoji: "🪑",
  },
  {
    id: 7,
    name: "Premium Jasmine Rice 5kg",
    category: "groceries",
    price: 95000.0,
    emoji: "🍚",
  },
  {
    id: 8,
    name: "Cooking Oil 2L",
    category: "groceries",
    price: 35000.0,
    emoji: "🧴",
  },
  {
    id: 9,
    name: "Wireless Headphones",
    category: "electronics",
    price: 1200000.0,
    emoji: "🎧",
  },
  {
    id: 10,
    name: "Smart Watch Series 9",
    category: "electronics",
    price: 5500000.0,
    emoji: "⌚",
  },
  {
    id: 11,
    name: "Face Serum 30ml",
    category: "beauty",
    price: 125000.0,
    emoji: "🧪",
  },
  {
    id: 12,
    name: "Moisturizer Gel",
    category: "beauty",
    price: 85000.0,
    emoji: "🧴",
  },
  {
    id: 13,
    name: "Yoga Mat 6mm",
    category: "sports",
    price: 150000.0,
    emoji: "🧘",
  },
  {
    id: 14,
    name: "Dumbbell Set 5kg",
    category: "sports",
    price: 250000.0,
    emoji: "💪",
  },
  {
    id: 15,
    name: "Mechanical Keyboard",
    category: "electronics",
    price: 850000.0,
    emoji: "⌨️",
  },
  {
    id: 16,
    name: "Gaming Mouse",
    category: "electronics",
    price: 450000.0,
    emoji: "🖱️",
  },
  {
    id: 17,
    name: "Cotton Bed Sheet",
    category: "home",
    price: 250000.0,
    emoji: "🛏️",
  },
  {
    id: 18,
    name: "Electric Kettle",
    category: "home",
    price: 180000.0,
    emoji: "🫖",
  },
  {
    id: 19,
    name: "Sunscreen SPF 50",
    category: "beauty",
    price: 95000.0,
    emoji: "☀️",
  },
  {
    id: 20,
    name: "Leather Wallet",
    category: "fashion",
    price: 200000.0,
    emoji: "👛",
  },
];

export const dummyProductHistory: WarehouseHistory[] = [
  {
    id: 1,
    type: "IN",
    qty: 50,
    date: "2024-05-10T10:00:00Z",
    reference: "PO-2024-001",
    notes: "Barang datang dari Supplier A",
    user: "Admin",
  },
  {
    id: 2,
    type: "OUT",
    qty: 10,
    date: "2024-05-11T14:30:00Z",
    reference: "SO-2024-012",
    notes: "Penjualan ke Pelanggan X",
    user: "Staff",
  },
  {
    id: 3,
    type: "IN",
    qty: 20,
    date: "2024-05-12T09:15:00Z",
    reference: "RET-2024-005",
    notes: "Retur barang rusak dari Toko B",
    user: "Admin",
  },
  {
    id: 4,
    type: "OUT",
    qty: 5,
    date: "2024-05-13T11:45:00Z",
    reference: "ADJ-2024-002",
    notes: "Penyesuaian stok opname bulanan",
    user: "Manager",
  },
  {
    id: 5,
    type: "IN",
    qty: 100,
    date: "2024-05-14T08:00:00Z",
    reference: "PO-2024-002",
    notes: "Restock mingguan produk utama",
    user: "Staff",
  },
  {
    id: 6,
    type: "OUT",
    qty: 25,
    date: "2024-05-14T16:20:00Z",
    reference: "SO-2024-015",
    notes: "Pengiriman pesanan marketplace",
    user: "Staff",
  },
  {
    id: 7,
    type: "IN",
    qty: 15,
    date: "2024-05-15T10:30:00Z",
    reference: "TRF-2024-001",
    notes: "Transfer internal dari Gudang Pusat",
    user: "Supervisor",
  },
  {
    id: 8,
    type: "OUT",
    qty: 8,
    date: "2024-05-16T09:00:00Z",
    reference: "SO-2024-020",
    notes: "Pesanan grosir Toko Jaya",
    user: "Manager",
  },
  {
    id: 9,
    type: "IN",
    qty: 40,
    date: "2024-05-17T13:00:00Z",
    reference: "PO-2024-005",
    notes: "Penerimaan barang impor",
    user: "Admin",
  },
  {
    id: 10,
    type: "OUT",
    qty: 12,
    date: "2024-05-18T15:45:00Z",
    reference: "SO-2024-025",
    notes: "Pengambilan sampel promosi",
    user: "Staff",
  },
  {
    id: 11,
    type: "IN",
    qty: 60,
    date: "2024-05-19T11:20:00Z",
    reference: "PO-2024-008",
    notes: "Barang tambahan dari Vendor C",
    user: "Admin",
  },
  {
    id: 12,
    type: "OUT",
    qty: 30,
    date: "2024-05-20T10:00:00Z",
    reference: "SO-2024-030",
    notes: "Distribusi ke cabang Selatan",
    user: "Supervisor",
  },
  {
    id: 13,
    type: "IN",
    qty: 10,
    date: "2024-05-21T08:30:00Z",
    reference: "RET-2024-008",
    notes: "Retur salah kirim dari Customer",
    user: "Staff",
  },
  {
    id: 14,
    type: "OUT",
    qty: 2,
    date: "2024-05-21T17:00:00Z",
    reference: "ADJ-2024-005",
    notes: "Barang rusak ditemukan saat sortir",
    user: "Admin",
  },
  {
    id: 15,
    type: "IN",
    qty: 75,
    date: "2024-05-22T09:45:00Z",
    reference: "PO-2024-010",
    notes: "Stok persiapan promo Gajian",
    user: "Manager",
  },
  {
    id: 16,
    type: "OUT",
    qty: 45,
    date: "2024-05-23T14:00:00Z",
    reference: "SO-2024-035",
    notes: "Pengiriman besar agen luar kota",
    user: "Staff",
  },
  {
    id: 17,
    type: "IN",
    qty: 35,
    date: "2024-05-24T10:15:00Z",
    reference: "TRF-2024-005",
    notes: "Mutasi barang gudang cabang",
    user: "Supervisor",
  },
  {
    id: 18,
    type: "OUT",
    qty: 18,
    date: "2024-05-25T11:00:00Z",
    reference: "SO-2024-040",
    notes: "Penjualan langsung (Showroom)",
    user: "Staff",
  },
  {
    id: 19,
    type: "IN",
    qty: 55,
    date: "2024-05-26T13:30:00Z",
    reference: "PO-2024-015",
    notes: "Kiriman dari Supplier B",
    user: "Admin",
  },
  {
    id: 20,
    type: "OUT",
    qty: 20,
    date: "2024-05-27T15:00:00Z",
    reference: "SO-2024-045",
    notes: "Order via WhatsApp Corporate",
    user: "Manager",
  },
  {
    id: 21,
    type: "IN",
    qty: 12,
    date: "2024-05-28T09:00:00Z",
    reference: "RET-2024-012",
    notes: "Barang tidak sesuai spesifikasi",
    user: "Staff",
  },
  {
    id: 22,
    type: "OUT",
    qty: 6,
    date: "2024-05-29T10:45:00Z",
    reference: "ADJ-2024-010",
    notes: "Penyusutan barang (Evaporation)",
    user: "Admin",
  },
  {
    id: 23,
    type: "IN",
    qty: 90,
    date: "2024-05-30T08:00:00Z",
    reference: "PO-2024-020",
    notes: "Penerimaan rutin awal bulan",
    user: "Supervisor",
  },
  {
    id: 24,
    type: "OUT",
    qty: 38,
    date: "2024-05-30T16:30:00Z",
    reference: "SO-2024-050",
    notes: "Pengiriman borongan ekspedisi",
    user: "Staff",
  },
  {
    id: 25,
    type: "IN",
    qty: 28,
    date: "2024-05-31T11:00:00Z",
    reference: "TRF-2024-010",
    notes: "Stok sisa event pameran",
    user: "Admin",
  },
  {
    id: 26,
    type: "OUT",
    qty: 15,
    date: "2024-06-01T09:30:00Z",
    reference: "SO-2024-055",
    notes: "Pesanan kilat internal",
    user: "Manager",
  },
  {
    id: 27,
    type: "IN",
    qty: 44,
    date: "2024-06-02T14:00:00Z",
    reference: "PO-2024-025",
    notes: "Barang pengganti vendor",
    user: "Staff",
  },
  {
    id: 28,
    type: "OUT",
    qty: 22,
    date: "2024-06-03T13:15:00Z",
    reference: "SO-2024-060",
    notes: "Retribusi stok cabang",
    user: "Supervisor",
  },
  {
    id: 29,
    type: "IN",
    qty: 18,
    date: "2024-06-04T10:00:00Z",
    reference: "RET-2024-015",
    notes: "Barang rusak pengiriman ekspedisi",
    user: "Admin",
  },
  {
    id: 30,
    type: "OUT",
    qty: 10,
    date: "2024-06-05T15:30:00Z",
    reference: "ADJ-2024-015",
    notes: "Penghapusan aset kedaluwarsa",
    user: "Manager",
  },
];
