import type { MenuItem, OrderCard } from "@/stores/posStore";

export const MONTHS = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];
export const DAYS_30 = Array.from({ length: 30 }, (_, i) => String(i + 1));

export const dummyOrders: OrderCard[] = [
  {
    id: "F0028",
    table: "07",
    items: 3,
    time: "Just Now",
    status: "wait_list",
  },
  {
    id: "F0019",
    table: "09",
    items: 2,
    time: "25 mins ago",
    status: "wait_list",
  },
  {
    id: "F0031",
    table: "12",
    items: 5,
    time: "10 mins ago",
    status: "finish",
  },
  {
    id: "F0033",
    table: "15",
    items: 2,
    time: "5 mins ago",
    status: "wait_list",
  },
  {
    id: "F0034",
    table: "02",
    items: 6,
    time: "30 mins ago",
    status: "process",
  },
  {
    id: "F0035",
    table: "11",
    items: 3,
    time: "1 hour ago",
    status: "finish",
  },
  {
    id: "F0037",
    table: "08",
    items: 1,
    time: "Just Now",
    status: "wait_list",
  },
  {
    id: "F0038",
    table: "14",
    items: 4,
    time: "40 mins ago",
    status: "process",
  },
  {
    id: "F0039",
    table: "20",
    items: 5,
    time: "2 hours ago",
    status: "finish",
  },
  {
    id: "F0041",
    table: "16",
    items: 3,
    time: "1 min ago",
    status: "wait_list",
  },
  {
    id: "F0042",
    table: "06",
    items: 8,
    time: "20 mins ago",
    status: "process",
  },
  {
    id: "F0043",
    table: "18",
    items: 1,
    time: "45 mins ago",
    status: "finish",
  },
  {
    id: "F0045",
    table: "22",
    items: 2,
    time: "3 mins ago",
    status: "wait_list",
  },
  {
    id: "F0046",
    table: "25",
    items: 6,
    time: "35 mins ago",
    status: "process",
  },
  {
    id: "F0047",
    table: "13",
    items: 3,
    time: "1.5 hours ago",
    status: "finish",
  },
  {
    id: "F0049",
    table: "21",
    items: 2,
    time: "4 mins ago",
    status: "wait_list",
  },
  {
    id: "F0050",
    table: "28",
    items: 7,
    time: "50 mins ago",
    status: "process",
  },
  {
    id: "F0051",
    table: "30",
    items: 1,
    time: "3 hours ago",
    status: "finish",
  },
  {
    id: "F0053",
    table: "23",
    items: 4,
    time: "7 mins ago",
    status: "wait_list",
  },
  {
    id: "F0054",
    table: "09",
    items: 2,
    time: "55 mins ago",
    status: "process",
  },
  {
    id: "F0055",
    table: "12",
    items: 5,
    time: "2.5 hours ago",
    status: "finish",
  },
  {
    id: "F0057",
    table: "07",
    items: 2,
    time: "9 mins ago",
    status: "wait_list",
  },
  {
    id: "F0058",
    table: "15",
    items: 3,
    time: "1 hour ago",
    status: "process",
  },
  {
    id: "F0059",
    table: "01",
    items: 4,
    time: "4 hours ago",
    status: "finish",
  },
  {
    id: "F0061",
    table: "14",
    items: 1,
    time: "11 mins ago",
    status: "wait_list",
  },
  {
    id: "F0062",
    table: "20",
    items: 5,
    time: "1.2 hours ago",
    status: "process",
  },
  {
    id: "F0063",
    table: "04",
    items: 2,
    time: "5 hours ago",
    status: "finish",
  },
  {
    id: "F0065",
    table: "06",
    items: 8,
    time: "13 mins ago",
    status: "wait_list",
  },
  {
    id: "F0066",
    table: "18",
    items: 4,
    time: "1.4 hours ago",
    status: "process",
  },
  {
    id: "F0067",
    table: "10",
    items: 6,
    time: "6 hours ago",
    status: "finish",
  },
];

export const categories = [
  {
    key: "all",
    label: { id: "Semua", en: "All" },
    emoji: "📦",
    count: 250,
  },
  {
    key: "electronics",
    label: { id: "Elektronik", en: "Electronics" },
    emoji: "💻",
    count: 42,
  },
  {
    key: "fashion",
    label: { id: "Fashion", en: "Fashion" },
    emoji: "👕",
    count: 85,
  },
  {
    key: "home",
    label: { id: "Rumah Tangga", en: "Home & Living" },
    emoji: "🏠",
    count: 33,
  },
  {
    key: "groceries",
    label: { id: "Sembako", en: "Groceries" },
    emoji: "🛒",
    count: 110,
  },
  {
    key: "beauty",
    label: { id: "Kecantikan", en: "Beauty" },
    emoji: "💄",
    count: 15,
  },
  {
    key: "sports",
    label: { id: "Olahraga", en: "Sports" },
    emoji: "⚽",
    count: 12,
  },
  {
    key: "special",
    label: { id: "Promo Spesial", en: "Special Deals" },
    emoji: "🔥",
    count: 8,
  },
];

export const dummyMenuItems: MenuItem[] = [
  {
    id: 1,
    name: "MacBook Pro M3",
    category: "electronics",
    price: 25000000.0,
    emoji: "💻",
  },
  {
    id: 2,
    name: "iPhone 15 Pro",
    category: "electronics",
    price: 18000000.0,
    emoji: "📱",
  },
  {
    id: 3,
    name: "Oversized T-Shirt",
    category: "fashion",
    price: 150000.0,
    emoji: "👕",
  },
  {
    id: 4,
    name: "Denim Jacket",
    category: "fashion",
    price: 450000.0,
    emoji: "🧥",
  },
  {
    id: 5,
    name: "Air Fryer 4L",
    category: "home",
    price: 850000.0,
    emoji: "🍳",
  },
  {
    id: 6,
    name: "Ergonomic Chair",
    category: "home",
    price: 1200000.0,
    emoji: "🪑",
  },
  {
    id: 7,
    name: "Premium Jasmine Rice 5kg",
    category: "groceries",
    price: 95000.0,
    emoji: "🍚",
  },
  {
    id: 8,
    name: "Cooking Oil 2L",
    category: "groceries",
    price: 35000.0,
    emoji: "🧴",
  },
  {
    id: 9,
    name: "Wireless Headphones",
    category: "electronics",
    price: 1200000.0,
    emoji: "🎧",
  },
  {
    id: 10,
    name: "Smart Watch Series 9",
    category: "electronics",
    price: 5500000.0,
    emoji: "⌚",
  },
  {
    id: 11,
    name: "Face Serum 30ml",
    category: "beauty",
    price: 125000.0,
    emoji: "🧪",
  },
  {
    id: 12,
    name: "Moisturizer Gel",
    category: "beauty",
    price: 85000.0,
    emoji: "🧴",
  },
  {
    id: 13,
    name: "Yoga Mat 6mm",
    category: "sports",
    price: 150000.0,
    emoji: "🧘",
  },
  {
    id: 14,
    name: "Dumbbell Set 5kg",
    category: "sports",
    price: 250000.0,
    emoji: "💪",
  },
  {
    id: 15,
    name: "Mechanical Keyboard",
    category: "electronics",
    price: 850000.0,
    emoji: "⌨️",
  },
  {
    id: 16,
    name: "Gaming Mouse",
    category: "electronics",
    price: 450000.0,
    emoji: "🖱️",
  },
  {
    id: 17,
    name: "Cotton Bed Sheet",
    category: "home",
    price: 250000.0,
    emoji: "🛏️",
  },
  {
    id: 18,
    name: "Electric Kettle",
    category: "home",
    price: 180000.0,
    emoji: "🫖",
  },
  {
    id: 19,
    name: "Sunscreen SPF 50",
    category: "beauty",
    price: 95000.0,
    emoji: "☀️",
  },
  {
    id: 20,
    name: "Leather Wallet",
    category: "fashion",
    price: 200000.0,
    emoji: "👛",
  },
];

export const dummyProductHistory = [
  {
    id: 1,
    type: "IN",
    qty: 50,
    date: "2024-05-10 10:00",
    reference: "PO-2024-001",
    notes: "Barang datang dari Supplier A",
    user: "Admin",
    status: "Completed",
  },
  {
    id: 2,
    type: "OUT",
    qty: 10,
    date: "2024-05-11 14:30",
    reference: "SO-2024-012",
    notes: "Penjualan ke Pelanggan X",
    user: "Staff",
    status: "Completed",
  },
  {
    id: 3,
    type: "IN",
    qty: 20,
    date: "2024-05-12 09:15",
    reference: "RET-2024-005",
    notes: "Retur barang rusak",
    user: "Admin",
    status: "Completed",
  },
  {
    id: 4,
    type: "OUT",
    qty: 5,
    date: "2024-05-13 11:45",
    reference: "ADJ-2024-002",
    notes: "Penyesuaian stok opname",
    user: "Manager",
    status: "Completed",
  },
];
