import * as flags from "country-flag-icons/react/3x2";
import { LanguageKey, type Language, type Country } from "@/types/world";

export const languages: Record<LanguageKey, Language> = {
  [LanguageKey.EN]: {
    name: "English",
    flag: "US" as keyof typeof flags,
  },
  [LanguageKey.ID]: {
    name: "Indonesian",
    flag: "ID" as keyof typeof flags,
  },
  [LanguageKey.MS]: {
    name: "Malay",
    flag: "MY" as keyof typeof flags,
  },
  [LanguageKey.TH]: {
    name: "Thai",
    flag: "TH" as keyof typeof flags,
  },
  [LanguageKey.FIL]: {
    name: "Filipino",
    flag: "PH" as keyof typeof flags,
  },
  [LanguageKey.VI]: {
    name: "Vietnamese",
    flag: "VN" as keyof typeof flags,
  },
  [LanguageKey.ZH]: {
    name: "Chinese",
    flag: "CN" as keyof typeof flags,
  },
  [LanguageKey.JA]: {
    name: "Japanese",
    flag: "JP" as keyof typeof flags,
  },
  [LanguageKey.KO]: {
    name: "Korean",
    flag: "KR" as keyof typeof flags,
  },
  [LanguageKey.HI]: {
    name: "Hindi",
    flag: "IN" as keyof typeof flags,
  },
  [LanguageKey.FR]: {
    name: "French",
    flag: "FR" as keyof typeof flags,
  },
  [LanguageKey.DE]: {
    name: "German",
    flag: "DE" as keyof typeof flags,
  },
  [LanguageKey.IT]: {
    name: "Italian",
    flag: "IT" as keyof typeof flags,
  },
  [LanguageKey.ES]: {
    name: "Spanish",
    flag: "ES" as keyof typeof flags,
  },
  [LanguageKey.PT]: {
    name: "Portuguese",
    flag: "PT" as keyof typeof flags,
  },
  [LanguageKey.NL]: {
    name: "Dutch",
    flag: "NL" as keyof typeof flags,
  },
  [LanguageKey.RU]: {
    name: "Russian",
    flag: "RU" as keyof typeof flags,
  },
  [LanguageKey.AR]: {
    name: "Arabic",
    flag: "SA" as keyof typeof flags,
  },
  [LanguageKey.TR]: {
    name: "Turkish",
    flag: "TR" as keyof typeof flags,
  },
  [LanguageKey.PL]: {
    name: "Polish",
    flag: "PL" as keyof typeof flags,
  },
  [LanguageKey.SV]: {
    name: "Swedish",
    flag: "SE" as keyof typeof flags,
  },
  [LanguageKey.NO]: {
    name: "Norwegian",
    flag: "NO" as keyof typeof flags,
  },
  [LanguageKey.DA]: {
    name: "Danish",
    flag: "DK" as keyof typeof flags,
  },
  [LanguageKey.FI]: {
    name: "Finnish",
    flag: "FI" as keyof typeof flags,
  },
  [LanguageKey.EL]: {
    name: "Greek",
    flag: "GR" as keyof typeof flags,
  },
  [LanguageKey.CS]: {
    name: "Czech",
    flag: "CZ" as keyof typeof flags,
  },
  [LanguageKey.HU]: {
    name: "Hungarian",
    flag: "HU" as keyof typeof flags,
  },
  [LanguageKey.RO]: {
    name: "Romanian",
    flag: "RO" as keyof typeof flags,
  },
  [LanguageKey.UK]: {
    name: "Ukrainian",
    flag: "UA" as keyof typeof flags,
  },
  [LanguageKey.HE]: {
    name: "Hebrew",
    flag: "IL" as keyof typeof flags,
  },
  [LanguageKey.UR]: {
    name: "Urdu",
    flag: "PK" as keyof typeof flags,
  },
  [LanguageKey.BN]: {
    name: "Bengali",
    flag: "BD" as keyof typeof flags,
  },
  [LanguageKey.SI]: {
    name: "Sinhala",
    flag: "LK" as keyof typeof flags,
  },
  [LanguageKey.MY]: {
    name: "Burmese",
    flag: "MM" as keyof typeof flags,
  },
  [LanguageKey.KM]: {
    name: "Khmer",
    flag: "KH" as keyof typeof flags,
  },
  [LanguageKey.LO]: {
    name: "Lao",
    flag: "LA" as keyof typeof flags,
  },
  [LanguageKey.NE]: {
    name: "Nepali",
    flag: "NP" as keyof typeof flags,
  },
  [LanguageKey.AM]: {
    name: "Amharic",
    flag: "ET" as keyof typeof flags,
  },
  [LanguageKey.SW]: {
    name: "Swahili",
    flag: "KE" as keyof typeof flags,
  },
  [LanguageKey.FA]: {
    name: "Persian",
    flag: "IR" as keyof typeof flags,
  },
  [LanguageKey.TA]: {
    name: "Tamil",
    flag: "IN" as keyof typeof flags,
  },
  [LanguageKey.TE]: {
    name: "Telugu",
    flag: "IN" as keyof typeof flags,
  },
  [LanguageKey.MR]: {
    name: "Marathi",
    flag: "IN" as keyof typeof flags,
  },
  [LanguageKey.GU]: {
    name: "Gujarati",
    flag: "IN" as keyof typeof flags,
  },
  [LanguageKey.PA]: {
    name: "Punjabi",
    flag: "IN" as keyof typeof flags,
  },
  [LanguageKey.JV]: {
    name: "Javanese",
    flag: "ID" as keyof typeof flags,
  },
  [LanguageKey.SU]: {
    name: "Sundanese",
    flag: "ID" as keyof typeof flags,
  },
  [LanguageKey.UZ]: {
    name: "Uzbek",
    flag: "UZ" as keyof typeof flags,
  },
  [LanguageKey.AZ]: {
    name: "Azerbaijani",
    flag: "AZ" as keyof typeof flags,
  },
  [LanguageKey.KK]: {
    name: "Kazakh",
    flag: "KZ" as keyof typeof flags,
  },
  [LanguageKey.BG]: {
    name: "Bulgarian",
    flag: "BG" as keyof typeof flags,
  },
  [LanguageKey.SR]: {
    name: "Serbian",
    flag: "RS" as keyof typeof flags,
  },
  [LanguageKey.HR]: {
    name: "Croatian",
    flag: "HR" as keyof typeof flags,
  },
  [LanguageKey.SK]: {
    name: "Slovak",
    flag: "SK" as keyof typeof flags,
  },
  [LanguageKey.LT]: {
    name: "Lithuanian",
    flag: "LT" as keyof typeof flags,
  },
  [LanguageKey.LV]: {
    name: "Latvian",
    flag: "LV" as keyof typeof flags,
  },
  [LanguageKey.ET]: {
    name: "Estonian",
    flag: "EE" as keyof typeof flags,
  },
  [LanguageKey.IS]: {
    name: "Icelandic",
    flag: "IS" as keyof typeof flags,
  },
  [LanguageKey.GA]: {
    name: "Irish",
    flag: "IE" as keyof typeof flags,
  },
  [LanguageKey.CY]: {
    name: "Welsh",
    flag: "GB" as keyof typeof flags,
  },
  [LanguageKey.MT]: {
    name: "Maltese",
    flag: "MT" as keyof typeof flags,
  },
  [LanguageKey.SQ]: {
    name: "Albanian",
    flag: "AL" as keyof typeof flags,
  },
  [LanguageKey.MK]: {
    name: "Macedonian",
    flag: "MK" as keyof typeof flags,
  },
  [LanguageKey.BS]: {
    name: "Bosnian",
    flag: "BA" as keyof typeof flags,
  },
  [LanguageKey.SL]: {
    name: "Slovenian",
    flag: "SI" as keyof typeof flags,
  },
  [LanguageKey.KA]: {
    name: "Georgian",
    flag: "GE" as keyof typeof flags,
  },
  [LanguageKey.HY]: {
    name: "Armenian",
    flag: "AM" as keyof typeof flags,
  },
  [LanguageKey.EU]: {
    name: "Basque",
    flag: "ES" as keyof typeof flags,
  },
  [LanguageKey.CA]: {
    name: "Catalan",
    flag: "ES" as keyof typeof flags,
  },
  [LanguageKey.GL]: {
    name: "Galician",
    flag: "ES" as keyof typeof flags,
  },
};
export const arrayLanguages = Object.keys(languages).map((lang) => ({
  key: lang,
  name: languages[lang as LanguageKey].name,
  flag: languages[lang as LanguageKey].flag,
}));

export const countries: Country[] = [
  {
    code: "US",
    name: "United States",
    language_key: LanguageKey.EN,
    phoneCode: 1,
    flag: "US" as keyof typeof flags,
  },
  {
    code: "ID",
    name: "Indonesia",
    language_key: LanguageKey.ID,
    phoneCode: 62,
    flag: "ID" as keyof typeof flags,
  },
  {
    code: "GB",
    name: "United Kingdom",
    language_key: LanguageKey.EN,
    phoneCode: 44,
    flag: "GB" as keyof typeof flags,
  },
  {
    code: "MY",
    name: "Malaysia",
    language_key: LanguageKey.MS,
    phoneCode: 60,
    flag: "MY" as keyof typeof flags,
  },
  {
    code: "SG",
    name: "Singapore",
    language_key: LanguageKey.EN,
    phoneCode: 65,
    flag: "SG" as keyof typeof flags,
  },
  {
    code: "TH",
    name: "Thailand",
    language_key: LanguageKey.TH,
    phoneCode: 66,
    flag: "TH" as keyof typeof flags,
  },
  {
    code: "PH",
    name: "Philippines",
    language_key: LanguageKey.FIL,
    phoneCode: 63,
    flag: "PH" as keyof typeof flags,
  },
  {
    code: "VN",
    name: "Vietnam",
    language_key: LanguageKey.VI,
    phoneCode: 84,
    flag: "VN" as keyof typeof flags,
  },
  {
    code: "CN",
    name: "China",
    language_key: LanguageKey.ZH,
    phoneCode: 86,
    flag: "CN" as keyof typeof flags,
  },
  {
    code: "JP",
    name: "Japan",
    language_key: LanguageKey.JA,
    phoneCode: 81,
    flag: "JP" as keyof typeof flags,
  },
  {
    code: "KR",
    name: "South Korea",
    language_key: LanguageKey.KO,
    phoneCode: 82,
    flag: "KR" as keyof typeof flags,
  },
  {
    code: "IN",
    name: "India",
    language_key: LanguageKey.HI,
    phoneCode: 91,
    flag: "IN" as keyof typeof flags,
  },
  {
    code: "AU",
    name: "Australia",
    language_key: LanguageKey.EN,
    phoneCode: 61,
    flag: "AU" as keyof typeof flags,
  },
  {
    code: "NZ",
    name: "New Zealand",
    language_key: LanguageKey.EN,
    phoneCode: 64,
    flag: "NZ" as keyof typeof flags,
  },
  {
    code: "FR",
    name: "France",
    language_key: LanguageKey.FR,
    phoneCode: 33,
    flag: "FR" as keyof typeof flags,
  },
  {
    code: "DE",
    name: "Germany",
    language_key: LanguageKey.DE,
    phoneCode: 49,
    flag: "DE" as keyof typeof flags,
  },
  {
    code: "IT",
    name: "Italy",
    language_key: LanguageKey.IT,
    phoneCode: 39,
    flag: "IT" as keyof typeof flags,
  },
  {
    code: "ES",
    name: "Spain",
    language_key: LanguageKey.ES,
    phoneCode: 34,
    flag: "ES" as keyof typeof flags,
  },
  {
    code: "PT",
    name: "Portugal",
    language_key: LanguageKey.PT,
    phoneCode: 351,
    flag: "PT" as keyof typeof flags,
  },
  {
    code: "NL",
    name: "Netherlands",
    language_key: LanguageKey.NL,
    phoneCode: 31,
    flag: "NL" as keyof typeof flags,
  },
  {
    code: "BR",
    name: "Brazil",
    language_key: LanguageKey.PT,
    phoneCode: 55,
    flag: "BR" as keyof typeof flags,
  },
  {
    code: "MX",
    name: "Mexico",
    language_key: LanguageKey.ES,
    phoneCode: 52,
    flag: "MX" as keyof typeof flags,
  },
  {
    code: "AR",
    name: "Argentina",
    language_key: LanguageKey.ES,
    phoneCode: 54,
    flag: "AR" as keyof typeof flags,
  },
  {
    code: "RU",
    name: "Russia",
    language_key: LanguageKey.RU,
    phoneCode: 7,
    flag: "RU" as keyof typeof flags,
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    language_key: LanguageKey.AR,
    phoneCode: 966,
    flag: "SA" as keyof typeof flags,
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    language_key: LanguageKey.AR,
    phoneCode: 971,
    flag: "AE" as keyof typeof flags,
  },
  {
    code: "TR",
    name: "Turkey",
    language_key: LanguageKey.TR,
    phoneCode: 90,
    flag: "TR" as keyof typeof flags,
  },
  {
    code: "EG",
    name: "Egypt",
    language_key: LanguageKey.AR,
    phoneCode: 20,
    flag: "EG" as keyof typeof flags,
  },
  {
    code: "ZA",
    name: "South Africa",
    language_key: LanguageKey.EN,
    phoneCode: 27,
    flag: "ZA" as keyof typeof flags,
  },
  {
    code: "CA",
    name: "Canada",
    language_key: LanguageKey.EN,
    phoneCode: 1,
    flag: "CA" as keyof typeof flags,
  },
  {
    code: "PL",
    name: "Poland",
    language_key: LanguageKey.PL,
    phoneCode: 48,
    flag: "PL" as keyof typeof flags,
  },
  {
    code: "SE",
    name: "Sweden",
    language_key: LanguageKey.SV,
    phoneCode: 46,
    flag: "SE" as keyof typeof flags,
  },
  {
    code: "NO",
    name: "Norway",
    language_key: LanguageKey.NO,
    phoneCode: 47,
    flag: "NO" as keyof typeof flags,
  },
  {
    code: "DK",
    name: "Denmark",
    language_key: LanguageKey.DA,
    phoneCode: 45,
    flag: "DK" as keyof typeof flags,
  },
  {
    code: "FI",
    name: "Finland",
    language_key: LanguageKey.FI,
    phoneCode: 358,
    flag: "FI" as keyof typeof flags,
  },
  {
    code: "GR",
    name: "Greece",
    language_key: LanguageKey.EL,
    phoneCode: 30,
    flag: "GR" as keyof typeof flags,
  },
  {
    code: "CZ",
    name: "Czechia",
    language_key: LanguageKey.CS,
    phoneCode: 420,
    flag: "CZ" as keyof typeof flags,
  },
  {
    code: "HU",
    name: "Hungary",
    language_key: LanguageKey.HU,
    phoneCode: 36,
    flag: "HU" as keyof typeof flags,
  },
  {
    code: "RO",
    name: "Romania",
    language_key: LanguageKey.RO,
    phoneCode: 40,
    flag: "RO" as keyof typeof flags,
  },
  {
    code: "UA",
    name: "Ukraine",
    language_key: LanguageKey.UK,
    phoneCode: 380,
    flag: "UA" as keyof typeof flags,
  },
  {
    code: "IL",
    name: "Israel",
    language_key: LanguageKey.HE,
    phoneCode: 972,
    flag: "IL" as keyof typeof flags,
  },
  {
    code: "PK",
    name: "Pakistan",
    language_key: LanguageKey.UR,
    phoneCode: 92,
    flag: "PK" as keyof typeof flags,
  },
  {
    code: "BD",
    name: "Bangladesh",
    language_key: LanguageKey.BN,
    phoneCode: 880,
    flag: "BD" as keyof typeof flags,
  },
  {
    code: "LK",
    name: "Sri Lanka",
    language_key: LanguageKey.SI,
    phoneCode: 94,
    flag: "LK" as keyof typeof flags,
  },
  {
    code: "MM",
    name: "Myanmar",
    language_key: LanguageKey.MY,
    phoneCode: 95,
    flag: "MM" as keyof typeof flags,
  },
  {
    code: "KH",
    name: "Cambodia",
    language_key: LanguageKey.KM,
    phoneCode: 855,
    flag: "KH" as keyof typeof flags,
  },
  {
    code: "LA",
    name: "Laos",
    language_key: LanguageKey.LO,
    phoneCode: 856,
    flag: "LA" as keyof typeof flags,
  },
  {
    code: "NP",
    name: "Nepal",
    language_key: LanguageKey.NE,
    phoneCode: 977,
    flag: "NP" as keyof typeof flags,
  },
  {
    code: "NG",
    name: "Nigeria",
    language_key: LanguageKey.EN,
    phoneCode: 234,
    flag: "NG" as keyof typeof flags,
  },
  {
    code: "KE",
    name: "Kenya",
    language_key: LanguageKey.EN,
    phoneCode: 254,
    flag: "KE" as keyof typeof flags,
  },
  {
    code: "GH",
    name: "Ghana",
    language_key: LanguageKey.EN,
    phoneCode: 233,
    flag: "GH" as keyof typeof flags,
  },
  {
    code: "ET",
    name: "Ethiopia",
    language_key: LanguageKey.AM,
    phoneCode: 251,
    flag: "ET" as keyof typeof flags,
  },
  {
    code: "TZ",
    name: "Tanzania",
    language_key: LanguageKey.SW,
    phoneCode: 255,
    flag: "TZ" as keyof typeof flags,
  },
  {
    code: "UG",
    name: "Uganda",
    language_key: LanguageKey.EN,
    phoneCode: 256,
    flag: "UG" as keyof typeof flags,
  },
  {
    code: "MA",
    name: "Morocco",
    language_key: LanguageKey.AR,
    phoneCode: 212,
    flag: "MA" as keyof typeof flags,
  },
  {
    code: "DZ",
    name: "Algeria",
    language_key: LanguageKey.AR,
    phoneCode: 213,
    flag: "DZ" as keyof typeof flags,
  },
  {
    code: "TN",
    name: "Tunisia",
    language_key: LanguageKey.AR,
    phoneCode: 216,
    flag: "TN" as keyof typeof flags,
  },
  {
    code: "CL",
    name: "Chile",
    language_key: LanguageKey.ES,
    phoneCode: 56,
    flag: "CL" as keyof typeof flags,
  },
  {
    code: "CO",
    name: "Colombia",
    language_key: LanguageKey.ES,
    phoneCode: 57,
    flag: "CO" as keyof typeof flags,
  },
  {
    code: "PE",
    name: "Peru",
    language_key: LanguageKey.ES,
    phoneCode: 51,
    flag: "PE" as keyof typeof flags,
  },
  {
    code: "VE",
    name: "Venezuela",
    language_key: LanguageKey.ES,
    phoneCode: 58,
    flag: "VE" as keyof typeof flags,
  },
  {
    code: "IE",
    name: "Ireland",
    language_key: LanguageKey.EN,
    phoneCode: 353,
    flag: "IE" as keyof typeof flags,
  },
  {
    code: "BE",
    name: "Belgium",
    language_key: LanguageKey.NL,
    phoneCode: 32,
    flag: "BE" as keyof typeof flags,
  },
  {
    code: "CH",
    name: "Switzerland",
    language_key: LanguageKey.DE,
    phoneCode: 41,
    flag: "CH" as keyof typeof flags,
  },
  {
    code: "AT",
    name: "Austria",
    language_key: LanguageKey.DE,
    phoneCode: 43,
    flag: "AT" as keyof typeof flags,
  },
].sort((a, b) => a.name.localeCompare(b.name));
